import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);  
		
		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.

		double average = 0;
		int two = 0;
		int three = 0;
		int four_or_more = 0;

		for (int j = 0; j < T; j++) {
			int gender = 0;
			int count = 0;
			boolean isBoy = true;
			if (generator.nextDouble() < 0.5) {
				gender = 0;
			}
			else {
				gender = 1;
			}

			if (gender == 1) {
				isBoy = false;
			}
			
			while (gender == 0) {
				count = count + 1;
				if (generator.nextDouble() < 0.5) {
					gender = 0;
				}
				else {
					gender = 1;
				}
			}
			while (gender == 1) {
				count = count + 1;
				if (generator.nextDouble() < 0.5) {
					gender = 0;
				}
				else {
					gender = 1;
				}
			}
			count = count + 1;

			average = average + count;

			if (count == 2) {
				two = two + 1;
			}
			else if (count == 3) {
				three = three + 1;
			}
			else if (count >= 4) {
				four_or_more = four_or_more + 1;
			}
		}	

		System.out.println("Average: " + average / T + " children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: " + two);
		System.out.println("Number of families with 3 children: " + three);
		System.out.println("Number of families with 4 or more children: " + four_or_more);
		
		int max = 0;
		if (two > max) {
			max = two;
		}
		if (three > max) {
			max = three;
		}
		if (four_or_more > max) {
			max = four_or_more;
		}

		if (max < 4) {
			System.out.println("The most common number of children is " + max + ".");
		}
		else {
			System.out.println("The most common number of children is 4 or more.");
		}
	}
}
